### ISSUE TITLE
Add jss-simple to the readme?

### ISSUE THREAD

**Issue by ashaffer** [jsstyles/jss#184]
I made a thing: [jss-simple](https://github.com/ashaffer/jss-simple). It makes it a bit nicer to work with JSS in the common case where you really only want a single global stylesheet, and it also makes it work a bit better with hot reloading (particularly if you use the [babel plugin](https://github.com/ashaffer/babel-plugin-jss-simple)).

**Comment by kof** [comment]
So in other words it handles attach/detach/toString of all styles at once.

**Comment by kof** [comment]
Well, why not. Some suggestions though: rename it to "global-jss". Global because its a more exact description, jss at the end, because jss-something is a plugin convention. This is not a plugin but a wrapper.

Regarding a link: I think we need a wiki page where everybody can add links to their pojects.

**Comment by kof** [comment]
Not sure though if it should be wiki or a documentation page in docs ...

Wiki is good because I don't need to merge requests. And its easier to add something.

Wiki is bad, because I would loos the control about how and what is posted there .... thoughts?

**Comment by kof** [comment]
done c1ce8b9bc4a224233a2b984a9f1cbecc1f133ae3
