### ISSUE TITLE
How to get rule prop with media queries context ?

### ISSUE THREAD

**Issue by maximelebreton** [jsstyles/jss#238]
```
export default {
  myDiv: {
    'min-height': 100
  },
  '@media (min-width: 768px)': {
    myDiv: {
      'min-height': 200
    }
  }
}
```

```
handleMouseUp() {
  var mouseY = 50; // static value for example
  var height = sheet.getRule('myDiv').prop('min-height') + mouseY;
  console.log(height);
}
```

#### **`result if window >= 768px:`** `150` `// nope, should be 250`

Is it possible to **dynamically** get the prop with media queries context?

**Comment by kof** [comment]
Right now we don't have a good api to access such rule. I am open for suggestions. The problem is that the rule inside of media context has the same name as a regular rule before.

You could do this sheet.getRule('@media (min-width: 768px)').rules.myDiv.prop('min-height') ... but this is an undocumented api and might break any time. Also it is ugly.

Another question is why would you need to to that.Isn't it better for your use case to manipulate element using inline styles? If no, you should at least create a non-media rule and manipulate it.
